<?php

use Drupal\commerce_order\Entity\OrderInterface;

/**
 * @file
 *
 * Commerce Crude Shipping module.
 */

/**
 * Implements hook_commerce_avatax_order_request_alter().
 *
 * @param array $request_body
 * @param \Drupal\commerce_order\Entity\OrderInterface $order
 */
function commerce_crude_shipping_commerce_avatax_order_request_alter(array &$request_body, OrderInterface $order) {
  foreach ($order->getItems() as $item) {
    foreach ($item->getAdjustments() as $adjustment) {
      if ($adjustment->getType() == 'shipping') {
        $request_body['lines'][] = [
          'number' => $item->id() . '_shipping',
          'quantity' => $item->getQuantity(),
          'amount' => $adjustment->getAmount()->getNumber(),
          // Shipping & Handling combined (taxable).
          'taxCode' => 'FR030000',
        ];
      }
    }
  }
}

    }
  }
}
